#!/bin/bash

set -eux -o pipefail

JOB_NAME=server
RUN_DIR=/var/vcap/sys/run/$JOB_NAME
LOG_DIR=/var/vcap/sys/log/$JOB_NAME
STDOUTLOG=$LOG_DIR/server.stdout.log
STDERRLOG=$LOG_DIR/server.stderr.log
PACKAGE_DIR=/var/vcap/packages
EPHEMERAL=/var/vcap/data/$JOB_NAME
PIDFILE=$RUN_DIR/$JOB_NAME.pid
RUNAS=vcap

export JAVA_HOME=$PACKAGE_DIR/jdk7

exec > >(tee -a $STDOUTLOG)
exec 2> >(tee -a $STDERRLOG)

case $1 in

  start)
    mkdir -p $RUN_DIR $LOG_DIR $EPHEMERAL
    chown -R $RUNAS:$RUNAS $RUN_DIR $LOG_DIR $EPHEMERAL

    $PACKAGE_DIR/apacheds2/bin/apacheds.sh start

    pgrep -a java | grep apacheds | awk '{print $1}' >$PIDFILE
    ;;

  stop)
    PID=$(head -1 $PIDFILE)
    if [ ! -z "$PID" ] && pid_exists "$PID"; then
      kill "$PID"
    fi
    while [ -e "/proc/$PID" ]; do sleep 0.1; done
    
    rm -f $PIDFILE
    ;;

  *)
    echo "Usage: ${JOB_NAME}_ctl {start|stop}" ;;
esac

